version: "3"

tasks:
  build:
    desc: Build
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/go_rest_api internal/main.go

  run:
    desc: Run
    cmds:
    - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: Generate Go code
    cmds:
    - GOFLAGS=-mod=mod go generate github.com/solomonbaez/SB-Go-Practice/go_rest_api/internal github.com/solomonbaez/SB-Go-Practice/go_rest_api/pkg/swagger

  swagger.validate:
    desc: Validate Go 
    cmds:
    - swagger validate pkg/swagger/swagger.yml

  swagger.doc:
    desc: Documentation
    cmds:
    - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html